#!/bin/bash
set -Eeuo pipefail

export $( grep -vE "^(#.*|\s*)$" .env )

git pull

ENV_DIR="./env"
if [ ! -d $ENV_DIR ]
then
	python3 -m venv env
fi

source env/bin/activate
apt-get install libjpeg-dev zlib1g-dev -y
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade pillow
python3 -m pip install -r requirements.txt

apt-get install nodejs -y
apt-get install npm -y

npm ci --dev

python3 manage.py collectstatic --noinput
python3 manage.py migrate

systemctl daemon-reload
systemctl restart star-burger
systemctl reload nginx

END_TIME="$(date)"

REVISION="$(git rev-parse HEAD)"
COMMENT="$(git log --format=%B -n 1 $REVISION)"
DIRECTORY="$(pwd)"
LOCAL_USER="$(whoami)"

if [ ! -z ${ROLLBAR_ACCESS_TOKEN+x} ];
then curl -H "X-Rollbar-Access-Token: $ROLLBAR_ACCESS_TOKEN" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d "{\"environment\": \"production\", \"revision\": \"$REVISION\", \"rollbar_name\": \"unknown\", \"local_username\": \"$LOCAL_USER\", \"comment\": \"$COMMENT\", \"status\": \"succeeded\", \"code_version\": \"$REVISION\", \"server\": {\"root\": \"file://$DIRECTORY/\"}}";
fi

echo "deploy success"
