# Generated by Django 3.2.15 on 2023-07-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0003_alter_geodata_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='address',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name='адрес'),
        ),
    ]
