# Generated by Django 3.2.15 on 2023-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='address',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='адрес'),
        ),
    ]
