# Generated by Django 3.2.15 on 2023-06-12 01:52

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20230612_0030'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('cost', django.db.models.manager.Manager()),
            ],
        ),
    ]
