# Generated by Django 3.2.15 on 2023-06-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_alter_order_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=34, verbose_name='прежняя цена'),
            preserve_default=False,
        ),
    ]
