# Generated by Django 3.2.15 on 2023-06-12 03:04

from django.db import migrations
from django.db.models import F


def fill_previous_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order_item in OrderItem.objects.all():
        order_item.previous_price = order_item.item.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_previous_price'),
    ]

    operations = [
        migrations.RunPython(fill_previous_prices),
    ]
