# Generated by Django 3.2.15 on 2023-06-12 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230612_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, max_digits=34, validators=[django.core.validators.MinValueValidator(0)], verbose_name='прежняя цена'),
        ),
    ]
