# Generated by Django 3.2.15 on 2023-07-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WM', 'Необработанный'), ('WR', 'Ожидание рестарана'), ('WC', 'Ожидание курьера'), ('CL', 'Завершён')], db_index=True, default='WM', max_length=2),
        ),
    ]
