# Generated by Django 3.2.15 on 2023-07-03 00:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20230702_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phoned_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='время создания заказа'),
        ),
    ]
