# Generated by Django 3.2.15 on 2023-07-03 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_order_payment_way'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reustaurant',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reustaurant_items', to='foodcartapp.restaurant', verbose_name='ресторан'),
            preserve_default=False,
        ),
    ]
