# Generated by Django 3.2.15 on 2023-07-03 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20230703_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reustaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reustaurant_items', to='foodcartapp.restaurant', verbose_name='ресторан'),
        ),
    ]
