# Generated by Django 3.2.15 on 2023-07-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0077_alter_order_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver_at',
            new_name='delivered_at',
        ),
    ]
