# Generated by Django 3.2.15 on 2023-07-02 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230612_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('WM', 'Необработанный'), ('WR', 'Ожидание рестарана'), ('WC', 'Ожидание курьера')], default='WM', max_length=2),
        ),
    ]
