# Generated by Django 3.2.15 on 2023-07-03 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0062_alter_orderitem_order_my'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_my',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='foodcartapp.order', verbose_name='заказ'),
        ),
    ]
