# Generated by Django 3.2.15 on 2023-07-18 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0063_auto_20230703_0216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='reustaurant',
            new_name='selected_reustaurant',
        ),
    ]
