# Generated by Django 3.2.15 on 2023-07-18 20:09

from django.db import migrations
from django.db.models import F


def change_nones(apps, schema_editor):
    Order = apps.get_model('foodcartapp', 'Order')
    Order.objects.update(
        comment='' if not F('comment') else F('comment'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0066_alter_order_comment'),
    ]

    operations = [
        migrations.RunPython(change_nones),
    ]
